### PR TITLE
Added support for IList to allow UI change the binding source :-)

### PR DESCRIPTION
**Pull request by smasihemami**
which is the case when using CheckedComboBox from Xceed WPF Toolkit)

### CODE REVIEW

**Comment by smasihemami** [comment]
There is one thing I was not sure about. On what to change in ListSlot.SetValue. But at least it worked to my expectations w.r.t CheckedComboBox.

**Comment by michaellperry** [comment]
Looks fantastic. I'll get a new build published. Thank you so much!

**Comment by smasihemami** [comment]
Thanks a lot Michael. Highly appreciate it :-)

**Comment by smasihemami** [comment]
On adding/removing items to an ObservableList, it seems to cast items to PlatformProxy which leads to InvalidCastException if the item type is not a primitive type. Do you have a guess on possible workarounds Michael?

**Comment by michaellperry** [comment]
I had not tested that scenario. That is the purpose of the call to `WrapValue` in `PublishChanges`. It is also the reason for `TranslateIncomingList` unwrapping the values.

I think that the same `UnwrapValue` call needs to appear in calls to `Add` and `Remove` in response to collection changed events. I expect that the control will take an item from the `ItemsSource` list and add it to the `SelectedItemsOverride` list. The item will be an instance of a platform proxy if the source item is an object as opposed to a primitive.

Please give this change a try. If it looks promising, I can give you access to the private NuGet repository so that you can test the fix before I push it up to nuget.org.

**Pull request merged**
